### ISSUE TITLE
Explorer is showing 2017 tokens only for those with 2017 and 2019 tokens.

### ISSUE THREAD

**Issue by ryanarndtcm** [blockstack/blockstack-explorer#176]
User has both 2019 and 2017 tokens, but the 2019 tokens are not displaying at all on the explorer

https://explorer.blockstack.org/address/stacks/SP1ERE1Z1MDVM100NWYR16GZZJJTZQYHG4F6GWBDM

Using https://explorer.blockstack.org/verifier shows the proper number of 2019 STX

2019 purchses alone (like this address SP107DZF5YNS59BNXYR9XVK00DFE0AZZAZPE3SGRR ) are showing up correctly in both verifier and explorer.

**Comment by hstove** [comment]
Hm, so this is only relevant for folks who were granted STX with no unlocking in the 2019 HF. I need to handle this case as well. Regular 2017 & 2019 investors are working (in staging)

**Comment by timstackblock** [comment]
This users account now says NaN STX in staging, the Total at this address is now broken. 

<img width="1428" alt="Screen Shot 2019-11-06 at 8 28 32 PM" src="https://user-images.githubusercontent.com/49165468/68352320-109cce00-00d4-11ea-9a51-c4c1bbac9f54.png">

In Prod they show 13,852.375 STX available at this address

<img width="1429" alt="Screen Shot 2019-11-06 at 8 29 33 PM" src="https://user-images.githubusercontent.com/49165468/68352403-4f328880-00d4-11ea-8bd7-de675a9e5986.png">

**Comment by hstove** [comment]
Tim has confirmed this is now fixed on staging.

**Comment by timstackblock** [comment]
<img width="1297" alt="Screen Shot 2019-11-08 at 1 35 15 PM" src="https://user-images.githubusercontent.com/49165468/68501663-a3e91700-022c-11ea-8035-f72972177540.png">

**Comment by timstackblock** [comment]
https://explorer.staging.blockstack.xyz/address/stacks/SP1ERE1Z1MDVM100NWYR16GZZJJTZQYHG4F6GWBDM



This calculation is ok except for token grants, I dont see the 5,245 in the calculation.

Unless its counted in the unlock or maybe received. 

When you ignore token grants everything adds up which means its not reflected in the total at this address ![Screen Shot 2019-11-08 at 6.09.55 PM.png](https://images.zenhubusercontent.com/5ca24ab84ae8ce257af826b8/aeb2c3fd-6a55-455d-bc48-6e7bdfdbb52a)

**Comment by hstove** [comment]
@timstackblock good catch, the "received" amount also included any "token grants", which is not accurate, and why the totals didn't add up. I've fixed that.

**Comment by timstackblock** [comment]
Ok thanks @hstove I will retest this now

**Comment by timstackblock** [comment]
NaN error is back I cant verify the calculations


<img width="894" alt="Screen Shot 2019-11-11 at 2 54 57 PM" src="https://user-images.githubusercontent.com/49165468/68616729-9c777700-0493-11ea-8f98-41ec028732b0.png">

**Comment by hstove** [comment]
Hey Tim - can you give it a shot again? I confirmed that staging is looking good again. I made some changes to the way our API connects to the database, which should prevent these database disconnection errors much less possible.

**Comment by timstackblock** [comment]
Looks good @hank
